# Fabric notebook source
# Generated by ssis-modernization-agent (Fabric target).
#
# Source SSIS package : ADDS-MIPS-TC
# Source Data Flow    : Data Flow Task
# SSIS components     : 2
#
# This stub MUST be hand-ported. The agent cannot translate Mapping
# Data Flow components to PySpark automatically. Treat each TODO
# block below as a checklist item.

# %% [markdown]
# # Data Flow Task
#
# Hand-ported from SSIS Data Flow Task in `ADDS-MIPS-TC`.
#
# **Original SSIS components (in declaration order):**
# - FlatFileDestination: CSV Output
# - OleDbSource: Data Source | table=[dbo].[activity]

# %% [code]
# Pipeline parameters arrive in the `parameters` dict the calling
# pipeline passes via the TridentNotebook activity. Add the names
# you actually consume here.
parameters = {  # noqa: E402 — Fabric injects this cell at runtime
    # "delta_column": None,
    # "key_columns": None,
}

# %% [code]
# --- 1. Read sources ---------------------------------------------------
# Source: Data Source (OleDbSource)
#   table = [dbo].[activity]
# TODO: replace with the real lakehouse path / SQL query for source #1
df_src_1 = spark.read.format('parquet').load('Files/TODO_path_to_Data Source')

# %% [code]
# --- 2. Apply transformations -----------------------------------------
# No SSIS transformations detected — straight pass-through.
df_out = df_src_1

# %% [code]
# --- 3. Write destinations --------------------------------------------
# Destination: CSV Output (FlatFileDestination)
#   table = TODO
#   keys  = TODO_KEY_COLUMN
# TODO: choose write mode — overwrite | append | merge.
# Lakehouse table example (overwrite):
df_out.write.mode('overwrite').format('delta').saveAsTable('TODO_target_1')

# %% [code]
mssparkutils.notebook.exit('OK')
