-- ============================================================================
--  Seed dbo.activity with the 69-column schema referenced by DS_Data_Source
--  and DF_Data_Flow_Task in the deployed MCPTest factory. Generates 300 rows
--  of plausible-but-fake test data so the data flow can be debugged
--  end-to-end without touching the real ADDS source.
--
--  Idempotent: drops & recreates the table on every run.
-- ============================================================================

IF OBJECT_ID(N'dbo.activity', N'U') IS NOT NULL
    DROP TABLE dbo.activity;
GO

CREATE TABLE dbo.activity (
    [Biennium]                    VARCHAR(4)   NOT NULL,
    [Agency]                      VARCHAR(3)   NOT NULL,
    [SubAgency]                   VARCHAR(1)   NULL,
    [Posting Fiscal Month]        VARCHAR(2)   NULL,
    [Posting Adjust Month]        INT          NULL,
    [ADDS Transaction Key]        INT          NOT NULL,
    [Account]                     VARCHAR(3)   NULL,
    [Account Detail]              VARCHAR(1)   NULL,
    [Organization Index]          VARCHAR(4)   NULL,
    [Expenditure Authority Index] VARCHAR(3)   NULL,
    [Program Index]               VARCHAR(5)   NULL,
    [PrePurge Project]            VARCHAR(4)   NULL,
    [PrePurge SubProject]         VARCHAR(2)   NULL,
    [PrePurge Project Phase]      VARCHAR(2)   NULL,
    [PrePurge Project Type]       VARCHAR(1)   NULL,
    [Transaction Code]            VARCHAR(3)   NULL,
    [Modifier]                    VARCHAR(1)   NULL,
    [Reverse Code]                VARCHAR(1)   NULL,
    [Master Index]                VARCHAR(8)   NULL,
    [OMWBE Pay Type]              VARCHAR(1)   NULL,
    [Master Index Percentage]     INT          NULL,
    [Variable GL Account]         VARCHAR(4)   NULL,
    [Input Fiscal Month]          VARCHAR(2)   NULL,
    [Input Adjusting Month]       INT          NULL,
    [Major Source]                VARCHAR(2)   NULL,
    [Source]                      VARCHAR(2)   NULL,
    [SubSource]                   VARCHAR(6)   NULL,
    [Object]                      VARCHAR(1)   NULL,
    [SubObject]                   VARCHAR(2)   NULL,
    [SubsubObject]                VARCHAR(4)   NULL,
    [Vendor Num]                  VARCHAR(10)  NULL,
    [Vendor Num Suffix]           VARCHAR(2)   NULL,
    [Vendor Name]                 VARCHAR(32)  NULL,
    [Contract Num]                VARCHAR(11)  NULL,
    [IRS Box]                     VARCHAR(1)   NULL,
    [Use Tax]                     VARCHAR(1)   NULL,
    [Agency Flag]                 VARCHAR(2)   NULL,
    [Vendor Trailer]              VARCHAR(4000) NULL,
    [Current Document Num]        VARCHAR(8)   NULL,
    [Current Document Num Suffix] VARCHAR(2)   NULL,
    [Doc Date]                    VARCHAR(30)  NULL,
    [Reference Doc Num]           VARCHAR(8)   NULL,
    [Reference Doc Num Suffix]    VARCHAR(2)   NULL,
    [Invoice Num]                 VARCHAR(30)  NULL,
    [Invoice Date]                VARCHAR(30)  NULL,
    [Order Num]                   VARCHAR(10)  NULL,
    [Workclass]                   VARCHAR(3)   NULL,
    [Budget Unit]                 VARCHAR(3)   NULL,
    [City]                        VARCHAR(4)   NULL,
    [County]                      VARCHAR(3)   NULL,
    [Month Of Service]            INT          NULL,
    [Allocation]                  VARCHAR(4)   NULL,
    [Submit Agency]               VARCHAR(3)   NULL,
    [Submit Subagency]            VARCHAR(1)   NULL,
    [Batch Date]                  VARCHAR(30)  NULL,
    [Batch Type]                  VARCHAR(2)   NULL,
    [Batch Num]                   VARCHAR(3)   NULL,
    [Batch Sequence Num]          VARCHAR(5)   NULL,
    [Dup Rec Ind]                 VARCHAR(1)   NULL,
    [Warrant Num]                 VARCHAR(7)   NULL,
    [Warrant Register Num]        INT          NULL,
    [Prompt Pay Date]             VARCHAR(8)   NULL,
    [Warrant Batch Fiscal Month]  VARCHAR(1)   NULL,
    [Warrant Batch Type]          VARCHAR(1)   NULL,
    [Warrant Batch Num]           VARCHAR(1)   NULL,
    [Process Date]                VARCHAR(16)  NULL,
    [TAPS Origin]                 VARCHAR(1)   NULL,
    [TAPS Status]                 VARCHAR(1)   NULL,
    [TAPS Packet Num]             VARCHAR(1)   NULL,
    [Account Num]                 VARCHAR(30)  NULL,
    CONSTRAINT PK_activity PRIMARY KEY CLUSTERED ([ADDS Transaction Key])
);
GO

-- ----------------------------------------------------------------------------
-- 300-row generator. Uses a numbers CTE so we don't need a procedural loop.
-- ----------------------------------------------------------------------------
;WITH n AS (
    SELECT TOP (300)
        ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS rn
    FROM sys.all_columns a CROSS JOIN sys.all_columns b
)
INSERT INTO dbo.activity (
    [Biennium], [Agency], [SubAgency], [Posting Fiscal Month],
    [Posting Adjust Month], [ADDS Transaction Key], [Account], [Account Detail],
    [Organization Index], [Expenditure Authority Index], [Program Index],
    [PrePurge Project], [PrePurge SubProject], [PrePurge Project Phase],
    [PrePurge Project Type], [Transaction Code], [Modifier], [Reverse Code],
    [Master Index], [OMWBE Pay Type], [Master Index Percentage],
    [Variable GL Account], [Input Fiscal Month], [Input Adjusting Month],
    [Major Source], [Source], [SubSource], [Object], [SubObject], [SubsubObject],
    [Vendor Num], [Vendor Num Suffix], [Vendor Name], [Contract Num],
    [IRS Box], [Use Tax], [Agency Flag], [Vendor Trailer],
    [Current Document Num], [Current Document Num Suffix], [Doc Date],
    [Reference Doc Num], [Reference Doc Num Suffix], [Invoice Num],
    [Invoice Date], [Order Num], [Workclass], [Budget Unit], [City], [County],
    [Month Of Service], [Allocation], [Submit Agency], [Submit Subagency],
    [Batch Date], [Batch Type], [Batch Num], [Batch Sequence Num],
    [Dup Rec Ind], [Warrant Num], [Warrant Register Num], [Prompt Pay Date],
    [Warrant Batch Fiscal Month], [Warrant Batch Type], [Warrant Batch Num],
    [Process Date], [TAPS Origin], [TAPS Status], [TAPS Packet Num],
    [Account Num]
)
SELECT
    '2526'                                                    AS [Biennium],
    RIGHT('000' + CAST((rn % 999) + 1 AS VARCHAR(3)), 3)      AS [Agency],
    CHAR(65 + (rn % 26))                                      AS [SubAgency],
    RIGHT('00' + CAST(((rn - 1) % 24) + 1 AS VARCHAR(2)), 2)  AS [Posting Fiscal Month],
    (rn % 12) + 1                                             AS [Posting Adjust Month],
    rn                                                        AS [ADDS Transaction Key],
    RIGHT('000' + CAST((rn * 7) % 999 AS VARCHAR(3)), 3)      AS [Account],
    CHAR(65 + (rn % 26))                                      AS [Account Detail],
    RIGHT('0000' + CAST((rn * 11) % 9999 AS VARCHAR(4)), 4)   AS [Organization Index],
    RIGHT('000' + CAST((rn * 3) % 999 AS VARCHAR(3)), 3)      AS [Expenditure Authority Index],
    RIGHT('00000' + CAST((rn * 13) % 99999 AS VARCHAR(5)), 5) AS [Program Index],
    RIGHT('0000' + CAST((rn * 17) % 9999 AS VARCHAR(4)), 4)   AS [PrePurge Project],
    RIGHT('00' + CAST(rn % 99 AS VARCHAR(2)), 2)              AS [PrePurge SubProject],
    RIGHT('00' + CAST((rn * 5) % 99 AS VARCHAR(2)), 2)        AS [PrePurge Project Phase],
    CHAR(65 + (rn % 5))                                       AS [PrePurge Project Type],
    RIGHT('000' + CAST((rn % 999) AS VARCHAR(3)), 3)          AS [Transaction Code],
    CASE WHEN rn % 7 = 0 THEN 'M' ELSE NULL END               AS [Modifier],
    CASE WHEN rn % 25 = 0 THEN 'R' ELSE NULL END              AS [Reverse Code],
    RIGHT('00000000' + CAST(rn AS VARCHAR(8)), 8)             AS [Master Index],
    CHAR(65 + (rn % 4))                                       AS [OMWBE Pay Type],
    (rn % 100) + 1                                            AS [Master Index Percentage],
    RIGHT('0000' + CAST((rn * 19) % 9999 AS VARCHAR(4)), 4)   AS [Variable GL Account],
    RIGHT('00' + CAST(((rn - 1) % 12) + 1 AS VARCHAR(2)), 2)  AS [Input Fiscal Month],
    (rn % 12) + 1                                             AS [Input Adjusting Month],
    RIGHT('00' + CAST((rn % 99) AS VARCHAR(2)), 2)            AS [Major Source],
    RIGHT('00' + CAST((rn % 99) AS VARCHAR(2)), 2)            AS [Source],
    RIGHT('000000' + CAST((rn * 23) % 999999 AS VARCHAR(6)), 6) AS [SubSource],
    CHAR(65 + (rn % 9))                                       AS [Object],
    RIGHT('00' + CAST((rn % 99) AS VARCHAR(2)), 2)            AS [SubObject],
    RIGHT('0000' + CAST((rn * 29) % 9999 AS VARCHAR(4)), 4)   AS [SubsubObject],
    RIGHT('0000000000' + CAST((rn * 31) AS VARCHAR(10)), 10)  AS [Vendor Num],
    RIGHT('00' + CAST(rn % 99 AS VARCHAR(2)), 2)              AS [Vendor Num Suffix],
    'Vendor ' + CAST(rn AS VARCHAR(8)) + ' Test Co.'          AS [Vendor Name],
    'C' + RIGHT('0000000000' + CAST(rn AS VARCHAR(10)), 10)   AS [Contract Num],
    '7'                                                       AS [IRS Box],
    'N'                                                       AS [Use Tax],
    'F1'                                                      AS [Agency Flag],
    REPLICATE('Trailer text segment ', 5)                     AS [Vendor Trailer],
    RIGHT('00000000' + CAST((rn * 37) AS VARCHAR(8)), 8)      AS [Current Document Num],
    RIGHT('00' + CAST(rn % 99 AS VARCHAR(2)), 2)              AS [Current Document Num Suffix],
    CONVERT(VARCHAR(30), DATEADD(DAY, -rn, '2026-01-01'), 121) AS [Doc Date],
    RIGHT('00000000' + CAST((rn * 41) AS VARCHAR(8)), 8)      AS [Reference Doc Num],
    RIGHT('00' + CAST(rn % 99 AS VARCHAR(2)), 2)              AS [Reference Doc Num Suffix],
    'INV-' + RIGHT('0000000000' + CAST(rn AS VARCHAR(10)), 10) AS [Invoice Num],
    CONVERT(VARCHAR(30), DATEADD(DAY, -rn, '2026-01-15'), 121) AS [Invoice Date],
    'PO-' + RIGHT('0000000' + CAST(rn AS VARCHAR(7)), 7)      AS [Order Num],
    RIGHT('000' + CAST((rn % 999) AS VARCHAR(3)), 3)          AS [Workclass],
    RIGHT('000' + CAST((rn % 999) AS VARCHAR(3)), 3)          AS [Budget Unit],
    RIGHT('0000' + CAST((rn * 43) % 9999 AS VARCHAR(4)), 4)   AS [City],
    RIGHT('000' + CAST((rn % 39) + 1 AS VARCHAR(3)), 3)       AS [County],
    (rn % 12) + 1                                             AS [Month Of Service],
    RIGHT('0000' + CAST((rn * 47) % 9999 AS VARCHAR(4)), 4)   AS [Allocation],
    RIGHT('000' + CAST((rn % 999) AS VARCHAR(3)), 3)          AS [Submit Agency],
    CHAR(65 + (rn % 26))                                      AS [Submit Subagency],
    CONVERT(VARCHAR(30), DATEADD(DAY, -rn, '2026-01-01'), 121) AS [Batch Date],
    CASE rn % 4 WHEN 0 THEN 'AP' WHEN 1 THEN 'GL' WHEN 2 THEN 'JE' ELSE 'IV' END AS [Batch Type],
    RIGHT('000' + CAST((rn % 999) AS VARCHAR(3)), 3)          AS [Batch Num],
    RIGHT('00000' + CAST(rn AS VARCHAR(5)), 5)                AS [Batch Sequence Num],
    CASE WHEN rn % 50 = 0 THEN 'D' ELSE 'N' END               AS [Dup Rec Ind],
    RIGHT('0000000' + CAST((rn * 53) % 9999999 AS VARCHAR(7)), 7) AS [Warrant Num],
    (rn % 9999) + 1                                           AS [Warrant Register Num],
    CONVERT(VARCHAR(8), DATEADD(DAY, rn, '2026-01-01'), 112)  AS [Prompt Pay Date],
    CHAR(48 + (rn % 10))                                      AS [Warrant Batch Fiscal Month],
    CHAR(65 + (rn % 5))                                       AS [Warrant Batch Type],
    CHAR(48 + (rn % 10))                                      AS [Warrant Batch Num],
    CONVERT(VARCHAR(16), DATEADD(MINUTE, rn, '2026-01-01'), 120) AS [Process Date],
    CHAR(65 + (rn % 4))                                       AS [TAPS Origin],
    CASE rn % 3 WHEN 0 THEN 'A' WHEN 1 THEN 'P' ELSE 'C' END  AS [TAPS Status],
    CHAR(48 + (rn % 10))                                      AS [TAPS Packet Num],
    'ACCT-' + RIGHT('0000000000000000000000000' + CAST(rn AS VARCHAR(25)), 25) AS [Account Num]
FROM n;
GO

PRINT CONCAT('Seeded dbo.activity with ', (SELECT COUNT(*) FROM dbo.activity), ' rows.');
GO
