"""
Azure Functions project generator — produces deployment-ready project files
around the per-function stubs generated by the Script Task and XML Task converters.

After conversion, the ``stubs/`` directory becomes a complete Azure Functions
project that can be deployed with ``func azure functionapp publish`` or
zip-deployed via CI/CD.

Generated files::

    stubs/
        host.json
        requirements.txt
        local.settings.json
        .funcignore
        <FunctionName>/
            __init__.py      ← already generated by converters
            function.json    ← already generated by converters
        ...
"""
from __future__ import annotations

import json
import re
from pathlib import Path

# Standard library modules that should NOT appear in requirements.txt
_STDLIB_MODULES = frozenset({
    "abc", "argparse", "ast", "asyncio", "base64", "collections", "contextlib",
    "copy", "csv", "datetime", "decimal", "enum", "functools", "glob",
    "hashlib", "http", "importlib", "inspect", "io", "itertools", "json",
    "logging", "math", "operator", "os", "pathlib", "pickle", "pprint",
    "random", "re", "shutil", "signal", "socket", "string", "struct", "sys",
    "tempfile", "textwrap", "threading", "time", "traceback", "typing",
    "unittest", "urllib", "uuid", "warnings", "xml", "zipfile",
})

# Known PyPI package name → import name mappings (import → package)
_IMPORT_TO_PACKAGE: dict[str, str] = {
    "azure.functions": "azure-functions",
    "azure": "azure-functions",
    "lxml": "lxml",
    "requests": "requests",
    "numpy": "numpy",
    "pandas": "pandas",
    "xmldiff": "xmldiff",
}

# Minimum versions for known packages
_PACKAGE_VERSIONS: dict[str, str] = {
    "azure-functions": "azure-functions>=1.17.0",
    "lxml": "lxml>=5.0.0",
    "requests": "requests>=2.31.0",
    "numpy": "numpy>=1.26.0",
    "pandas": "pandas>=2.1.0",
    "xmldiff": "xmldiff>=2.6.0",
}


def generate_func_project(stubs_dir: Path) -> dict[str, str]:
    """Generate Azure Functions project files in *stubs_dir*.

    Returns a dict mapping relative file paths to their purpose/description
    for inclusion in the conversion summary.

    Skips generation if *stubs_dir* does not exist or contains no functions.
    """
    if not stubs_dir.exists():
        return {}

    # Discover function directories (dirs containing __init__.py)
    func_dirs = [
        d for d in stubs_dir.iterdir()
        if d.is_dir() and (d / "__init__.py").exists()
    ]
    if not func_dirs:
        return {}

    generated: dict[str, str] = {}

    # 1. host.json
    host_json = stubs_dir / "host.json"
    if not host_json.exists():
        host_json.write_text(json.dumps({
            "version": "2.0",
            "logging": {
                "applicationInsights": {
                    "samplingSettings": {
                        "isEnabled": True,
                        "excludedTypes": "Request",
                    }
                }
            },
            "extensionBundle": {
                "id": "Microsoft.Azure.Functions.ExtensionBundle",
                "version": "[4.*, 5.0.0)",
            },
            "functionTimeout": "00:10:00",
        }, indent=2), encoding="utf-8")
        generated["host.json"] = "Azure Functions host config"

    # 2. requirements.txt — scan all stubs for imports
    req_file = stubs_dir / "requirements.txt"
    if not req_file.exists():
        imports = _scan_imports(func_dirs)
        packages = _resolve_packages(imports)
        # Always include azure-functions
        packages.add(_PACKAGE_VERSIONS.get("azure-functions", "azure-functions"))
        req_file.write_text(
            "# Auto-generated by ssis-adf-agent\n"
            "# Review and pin versions before deploying to production.\n"
            + "\n".join(sorted(packages)) + "\n",
            encoding="utf-8",
        )
        generated["requirements.txt"] = f"{len(packages)} packages detected"

    # 3. local.settings.json
    local_settings = stubs_dir / "local.settings.json"
    if not local_settings.exists():
        local_settings.write_text(json.dumps({
            "IsEncrypted": False,
            "Values": {
                "AzureWebJobsStorage": "",
                "FUNCTIONS_WORKER_RUNTIME": "python",
            },
        }, indent=2), encoding="utf-8")
        generated["local.settings.json"] = "Local dev settings (do not deploy)"

    # 4. .funcignore
    funcignore = stubs_dir / ".funcignore"
    if not funcignore.exists():
        funcignore.write_text(
            "# Auto-generated by ssis-adf-agent\n"
            ".git*\n"
            ".vscode\n"
            "__azurite_*\n"
            "local.settings.json\n"
            "test\n"
            ".venv\n"
            "*.pyc\n"
            "__pycache__\n",
            encoding="utf-8",
        )
        generated[".funcignore"] = "Deployment exclusion list"

    return generated


def _scan_imports(func_dirs: list[Path]) -> set[str]:
    """Scan all ``__init__.py`` files for top-level import statements."""
    imports: set[str] = set()
    import_re = re.compile(
        r"^\s*(?:import|from)\s+([\w.]+)", re.MULTILINE
    )
    for d in func_dirs:
        init = d / "__init__.py"
        if init.exists():
            text = init.read_text(encoding="utf-8", errors="replace")
            for m in import_re.finditer(text):
                module = m.group(1).split(".")[0]
                imports.add(module)
                # Also capture dotted imports for azure.functions etc.
                full = m.group(1)
                if "." in full:
                    imports.add(full)
    return imports


def _resolve_packages(imports: set[str]) -> set[str]:
    """Map import names to PyPI package specifiers."""
    packages: set[str] = set()
    for imp in imports:
        top = imp.split(".")[0]
        if top in _STDLIB_MODULES:
            continue
        # Try full dotted name first, then top-level
        pkg = _IMPORT_TO_PACKAGE.get(imp) or _IMPORT_TO_PACKAGE.get(top)
        if pkg:
            packages.add(_PACKAGE_VERSIONS.get(pkg, pkg))
        elif top not in _STDLIB_MODULES:
            # Unknown third-party import — include as-is so user can review
            packages.add(f"# {top}  # TODO: verify package name")
    return packages
