"""
Notebook stub generator — emits a Fabric PySpark notebook for each SSIS Data
Flow Task. Fabric Data Pipelines have no Mapping Data Flow equivalent, so
data flow logic must be ported by hand into a notebook the pipeline calls
via a TridentNotebook activity.

The stub is structured the way Fabric stores notebooks on disk: a
notebook-content.py file with %%-cell delimiters plus a `.platform` JSON
sidecar that names the notebook item. The deployer (or `fab import`) reads
this layout and creates a Fabric notebook item from it.

The stub deliberately:
  - preserves the SSIS DFT name and component list as comments so the
    engineer porting the logic has the original lineage in front of them
  - emits TODO blocks for each transformation type detected in the SSIS DFT
  - uses lakehouse.write semantics by default (the most common Fabric target)
  - never makes an opinionated choice about destination format / mode beyond
    a TODO — the engineer must decide
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..parsers.models import DataFlowComponent, DataFlowTask


def _component_table_name(comp: DataFlowComponent) -> str | None:
    """Best-effort extract of an SSIS source/destination table name."""
    props = comp.properties or {}
    for key in ("OpenRowset", "TableOrViewName", "TableName", "Table", "OpenRowsetVariable"):
        v = props.get(key)
        if isinstance(v, str) and v.strip():
            return v.strip()
    return None


def _component_summary(comp: DataFlowComponent) -> str:
    """One-line summary of a SSIS DataFlowComponent for the stub header."""
    parts = [f"{comp.component_type}: {comp.name}"]
    table = _component_table_name(comp)
    if table:
        parts.append(f"table={table}")
    if comp.key_columns:
        parts.append(f"keys={','.join(comp.key_columns)}")
    return " | ".join(parts)


def _classify_transforms(task: DataFlowTask) -> list[str]:
    """List the unique SSIS transformation component types in *task*."""
    transforms = []
    seen: set[str] = set()
    for c in task.components:
        ctype = c.component_type
        if ctype in seen:
            continue
        if ctype.endswith("Source") or ctype.endswith("Destination"):
            continue
        seen.add(ctype)
        transforms.append(ctype)
    return transforms


def _build_notebook_content(task: DataFlowTask, package_name: str) -> str:
    """Build the notebook-content.py text (PySpark, %%-cell delimited)."""
    lines: list[str] = []
    a = lines.append

    a("# Fabric notebook source")
    a("# Generated by ssis-modernization-agent (Fabric target).")
    a("#")
    a(f"# Source SSIS package : {package_name}")
    a(f"# Source Data Flow    : {task.name}")
    a(f"# SSIS components     : {len(task.components)}")
    a("#")
    a("# This stub MUST be hand-ported. The agent cannot translate Mapping")
    a("# Data Flow components to PySpark automatically. Treat each TODO")
    a("# block below as a checklist item.")
    a("")
    a("# %% [markdown]")
    a(f"# # {task.name}")
    a("#")
    a(f"# Hand-ported from SSIS Data Flow Task in `{package_name}`.")
    a("#")
    a("# **Original SSIS components (in declaration order):**")
    for comp in task.components:
        a(f"# - {_component_summary(comp)}")
    a("")
    a("# %% [code]")
    a("# Pipeline parameters arrive in the `parameters` dict the calling")
    a("# pipeline passes via the TridentNotebook activity. Add the names")
    a("# you actually consume here.")
    a("parameters = {  # noqa: E402 — Fabric injects this cell at runtime")
    a('    # "delta_column": None,')
    a('    # "key_columns": None,')
    a("}")
    a("")
    a("# %% [code]")
    a("# --- 1. Read sources ---------------------------------------------------")
    src_count = 0
    for comp in task.components:
        if comp.component_type.endswith("Source"):
            src_count += 1
            tbl = _component_table_name(comp) or "TODO"
            a(f"# Source: {comp.name} ({comp.component_type})")
            a(f"#   table = {tbl}")
            a(f"# TODO: replace with the real lakehouse path / SQL query for source #{src_count}")
            a(f"df_src_{src_count} = spark.read.format('parquet').load('Files/TODO_path_to_{comp.name}')")
            a("")
    if src_count == 0:
        a("# TODO: no SSIS sources detected; declare your input dataframes here")
        a("df_src_1 = None")
        a("")

    a("# %% [code]")
    a("# --- 2. Apply transformations -----------------------------------------")
    transforms = _classify_transforms(task)
    if not transforms:
        a("# No SSIS transformations detected — straight pass-through.")
        a("df_out = df_src_1")
    else:
        a("# Original SSIS transformations to port:")
        for t in transforms:
            a(f"#   - {t}")
        a("# TODO: implement the transformation chain. Common mappings:")
        a("#   DerivedColumn      -> df.withColumn(name, expr(...))")
        a("#   ConditionalSplit   -> df.filter(...) for each output branch")
        a("#   Lookup             -> df.join(lookup_df, on=..., how='left')")
        a("#   Aggregate          -> df.groupBy(...).agg(...)")
        a("#   Sort               -> df.orderBy(...)")
        a("#   UnionAll           -> df1.unionByName(df2)")
        a("#   MergeJoin          -> df1.join(df2, on=..., how='inner|left|outer')")
        a("#   DataConversion     -> df.withColumn(name, col(name).cast(t))")
        a("#   ScriptComponent    -> custom UDF; lift logic from the SSIS .vb / .cs source")
        a("df_out = df_src_1  # TODO: replace with the real transformation chain")
    a("")
    a("# %% [code]")
    a("# --- 3. Write destinations --------------------------------------------")
    dst_count = 0
    for comp in task.components:
        if comp.component_type.endswith("Destination"):
            dst_count += 1
            tbl = _component_table_name(comp)
            a(f"# Destination: {comp.name} ({comp.component_type})")
            a(f"#   table = {tbl or 'TODO'}")
            a(f"#   keys  = {','.join(comp.key_columns) or 'TODO_KEY_COLUMN'}")
            a("# TODO: choose write mode — overwrite | append | merge.")
            a("# Lakehouse table example (overwrite):")
            target = tbl or f"TODO_target_{dst_count}"
            a(f"df_out.write.mode('overwrite').format('delta').saveAsTable('{target}')")
            a("")
    if dst_count == 0:
        a("# TODO: no SSIS destinations detected; add the write step here")
        a("# df_out.write.mode('overwrite').format('delta').saveAsTable('TODO_target')")
        a("")
    a("# %% [code]")
    a("mssparkutils.notebook.exit('OK')")
    return "\n".join(lines) + "\n"


def _platform_metadata(task: DataFlowTask, package_name: str) -> dict[str, Any]:
    """The `.platform` sidecar Fabric expects next to notebook-content.py."""
    return {
        "$schema": "https://developer.microsoft.com/json-schemas/fabric/gitIntegration/platformProperties/2.0.0/schema.json",
        "metadata": {
            "type": "Notebook",
            "displayName": notebook_display_name(task, package_name),
            "description": (
                f"Hand-port stub for SSIS Data Flow Task '{task.name}' from "
                f"package '{package_name}'. Generated by ssis-modernization-agent."
            ),
        },
        "config": {"version": "2.0", "logicalId": ""},
    }


def notebook_display_name(task: DataFlowTask, package_name: str) -> str:
    """Stable display name for the Fabric notebook."""
    safe_pkg = package_name.replace(" ", "_")
    safe_task = task.name.replace(" ", "_")
    return f"NB_{safe_pkg}__{safe_task}"


def write_notebook_stub(
    task: DataFlowTask,
    package_name: str,
    notebooks_root: Path,
) -> Path:
    """Write a Fabric notebook stub for *task* under *notebooks_root*.

    Layout::

        notebooks_root/
            NB_<pkg>__<task>.Notebook/
                notebook-content.py
                .platform

    Returns the directory containing the notebook artifacts.
    """
    name = notebook_display_name(task, package_name)
    target = notebooks_root / f"{name}.Notebook"
    target.mkdir(parents=True, exist_ok=True)

    (target / "notebook-content.py").write_text(
        _build_notebook_content(task, package_name), encoding="utf-8"
    )
    (target / ".platform").write_text(
        json.dumps(_platform_metadata(task, package_name), indent=2),
        encoding="utf-8",
    )
    return target
