"""Estate-level PDF report — combines bulk_analyze + waves + costs.

This is the customer-facing handoff document. It deliberately does NOT include
per-package design details (which live in the per-package pre-migration PDF
generated by ``build_pre_migration_pdf``); instead it gives stakeholders the
"how big is this, how much will it cost, in what order do we do it" view.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
    _REPORTLAB_AVAILABLE = True
except ImportError:  # pragma: no cover - import guard
    _REPORTLAB_AVAILABLE = False


def _require_reportlab() -> None:
    if not _REPORTLAB_AVAILABLE:
        raise RuntimeError(
            "reportlab is required for PDF generation. Install it with:\n"
            "    pip install reportlab"
        )


def _styles() -> dict[str, "ParagraphStyle"]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("Title", parent=base["Title"], fontSize=22, leading=26, spaceAfter=12),
        "h1": ParagraphStyle("H1", parent=base["Heading1"], fontSize=16, spaceBefore=18, spaceAfter=6),
        "h2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=13, spaceBefore=12, spaceAfter=4),
        "body": ParagraphStyle("Body", parent=base["BodyText"], fontSize=10, leading=13),
        "small": ParagraphStyle("Small", parent=base["BodyText"], fontSize=9, leading=11, textColor=colors.grey),
    }


def _esc(text: Any) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _table(rows: list[list[str]], col_widths: list[float], header: bool = True) -> "Table":
    tbl = Table(rows, colWidths=col_widths)
    style = [
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
    ]
    if header:
        style += [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f3a93")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]
    tbl.setStyle(TableStyle(style))
    return tbl


def build_estate_report_pdf(
    *,
    output_pdf: str | Path,
    estate_report: dict[str, Any],
    waves: dict[str, Any] | None = None,
    cost_estimate: dict[str, Any] | None = None,
    customer_name: str | None = None,
) -> str:
    """Build the estate-level PDF and return the absolute output path."""
    _require_reportlab()
    out_path = Path(output_pdf).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    styles = _styles()

    doc = SimpleDocTemplate(
        str(out_path), pagesize=LETTER,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        topMargin=0.7 * inch, bottomMargin=0.6 * inch,
        title="SSIS estate migration report",
    )
    story: list[Any] = []

    # -- Cover --
    story.append(Paragraph("SSIS \u2192 ADF estate migration report", styles["title"]))
    if customer_name:
        story.append(Paragraph(f"Prepared for: <b>{_esc(customer_name)}</b>", styles["body"]))
    story.append(Paragraph(f"Generated: {datetime.now():%Y-%m-%d %H:%M}", styles["small"]))
    story.append(Spacer(1, 0.2 * inch))

    # -- Executive summary --
    summary = estate_report.get("estate_summary", {})
    by_bucket = summary.get("by_complexity_bucket", {})
    by_pattern = summary.get("by_target_pattern", {})

    story.append(Paragraph("Executive summary", styles["h1"]))
    exec_rows = [
        ["Metric", "Value"],
        ["Packages scanned", str(estate_report.get("package_count", 0))],
        ["Parse failures", str(estate_report.get("failure_count", 0))],
        ["Bulk-convertible (low/medium)", str(summary.get("bulk_convertible_count", 0))],
        ["Needs design review (high/very_high)", str(summary.get("needs_design_review_count", 0))],
        ["Estimated total effort (hours)", str(summary.get("estimated_total_hours", 0))],
        ["Manual-required items", str(summary.get("manual_required_total", 0))],
    ]
    if cost_estimate:
        exec_rows.append(["Projected monthly run cost (USD)", f"${cost_estimate.get('monthly_total_usd', 0):,.2f}"])
        exec_rows.append(["Projected annual run cost (USD)", f"${cost_estimate.get('annual_total_usd', 0):,.2f}"])
    story.append(_table(exec_rows, [3.0 * inch, 3.5 * inch]))
    story.append(Spacer(1, 0.2 * inch))

    # -- Complexity / pattern breakdown --
    story.append(Paragraph("Estate composition", styles["h1"]))
    story.append(Paragraph("By complexity bucket", styles["h2"]))
    bucket_rows = [["Bucket", "Packages"]] + [
        [b, str(by_bucket.get(b, 0))] for b in ("low", "medium", "high", "very_high")
    ]
    story.append(_table(bucket_rows, [2.0 * inch, 1.0 * inch]))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("By target pattern", styles["h2"]))
    pattern_rows = [["Target pattern", "Packages"]] + [
        [p, str(c)] for p, c in sorted(by_pattern.items(), key=lambda kv: -kv[1])
    ]
    story.append(_table(pattern_rows, [3.5 * inch, 1.0 * inch]))

    # -- Wave plan --
    if waves and waves.get("waves"):
        story.append(PageBreak())
        story.append(Paragraph("Recommended migration waves", styles["h1"]))
        story.append(Paragraph(
            f"{waves.get('wave_count', 0)} waves \u2014 "
            f"total estimated effort: {waves.get('total_estimated_hours', 0)}h",
            styles["body"],
        ))
        story.append(Spacer(1, 0.1 * inch))
        wave_rows = [["#", "Label", "Strategy", "Pkgs", "Hours"]]
        for w in waves["waves"]:
            wave_rows.append([
                str(w["wave"]),
                w["label"],
                w.get("strategy", ""),
                str(w["package_count"]),
                str(w["estimated_hours"]),
            ])
        story.append(_table(wave_rows, [0.4 * inch, 3.0 * inch, 1.4 * inch, 0.6 * inch, 0.8 * inch]))

    # -- Cost detail --
    if cost_estimate:
        story.append(PageBreak())
        story.append(Paragraph("Projected monthly cost (USD)", styles["h1"]))
        story.append(Paragraph(_esc(cost_estimate.get("note", "")), styles["small"]))
        story.append(Spacer(1, 0.1 * inch))
        cost_rows = [["Line item", "Monthly USD", "Basis"]]
        for li in cost_estimate.get("line_items", []):
            cost_rows.append([li["name"], f"${li['monthly_usd']:,.2f}", li["basis"]])
        cost_rows.append(["Total", f"${cost_estimate.get('monthly_total_usd', 0):,.2f}", ""])
        story.append(_table(cost_rows, [3.2 * inch, 1.2 * inch, 2.4 * inch]))

    # -- Per-package detail --
    story.append(PageBreak())
    story.append(Paragraph("Per-package detail", styles["h1"]))
    pkg_rows = [["Package", "Bucket", "Pattern", "Score", "Hours", "Manual"]]
    for p in estate_report.get("packages", []):
        pkg_rows.append([
            p.get("package_name", ""),
            p.get("complexity_bucket", ""),
            p.get("target_pattern", ""),
            str(p.get("complexity_score", "")),
            str(p.get("estimated_total_hours", "")),
            str(p.get("manual_required_count", 0)),
        ])
    story.append(_table(pkg_rows, [2.4 * inch, 0.8 * inch, 1.6 * inch, 0.6 * inch, 0.6 * inch, 0.6 * inch]))

    failures = estate_report.get("failures", [])
    if failures:
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Parse failures", styles["h2"]))
        for f in failures:
            story.append(Paragraph(f"\u2022 {_esc(f.get('path', '?'))} \u2014 {_esc(f.get('error', ''))}", styles["small"]))

    doc.build(story)
    return str(out_path)
