"""Estate-level PDF report — combines bulk_analyze + waves + costs.

This is the customer-facing handoff document. It deliberately does NOT include
per-package design details (which live in the per-package pre-migration PDF
generated by ``build_pre_migration_pdf``); instead it gives stakeholders the
"how big is this, how much will it cost, in what order do we do it" view.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )
    _REPORTLAB_AVAILABLE = True
except ImportError:  # pragma: no cover - import guard
    _REPORTLAB_AVAILABLE = False


def _require_reportlab() -> None:
    if not _REPORTLAB_AVAILABLE:
        raise RuntimeError(
            "reportlab is required for PDF generation. Install it with:\n"
            "    pip install reportlab"
        )


def _styles() -> dict[str, "ParagraphStyle"]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle("Title", parent=base["Title"], fontSize=22, leading=26, spaceAfter=12),
        "h1": ParagraphStyle("H1", parent=base["Heading1"], fontSize=16, spaceBefore=18, spaceAfter=6),
        "h2": ParagraphStyle("H2", parent=base["Heading2"], fontSize=13, spaceBefore=12, spaceAfter=4),
        "body": ParagraphStyle("Body", parent=base["BodyText"], fontSize=10, leading=13),
        "small": ParagraphStyle("Small", parent=base["BodyText"], fontSize=9, leading=11, textColor=colors.grey),
    }


def _esc(text: Any) -> str:
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _table(rows: list[list[str]], col_widths: list[float], header: bool = True) -> "Table":
    tbl = Table(rows, colWidths=col_widths)
    style = [
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
    ]
    if header:
        style += [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f3a93")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]
    tbl.setStyle(TableStyle(style))
    return tbl


def build_estate_report_pdf(
    *,
    output_pdf: str | Path,
    estate_report: dict[str, Any],
    waves: dict[str, Any] | None = None,
    cost_estimate: dict[str, Any] | None = None,
    customer_name: str | None = None,
) -> str:
    """Build the estate-level PDF and return the absolute output path."""
    _require_reportlab()
    out_path = Path(output_pdf).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    styles = _styles()

    doc = SimpleDocTemplate(
        str(out_path), pagesize=LETTER,
        leftMargin=0.6 * inch, rightMargin=0.6 * inch,
        topMargin=0.7 * inch, bottomMargin=0.6 * inch,
        title="SSIS estate migration report",
    )
    story: list[Any] = []

    # -- Cover --
    story.append(Paragraph("SSIS \u2192 ADF estate migration report", styles["title"]))
    if customer_name:
        story.append(Paragraph(f"Prepared for: <b>{_esc(customer_name)}</b>", styles["body"]))
    story.append(Paragraph(f"Generated: {datetime.now():%Y-%m-%d %H:%M}", styles["small"]))
    story.append(Spacer(1, 0.2 * inch))

    # -- Executive summary --
    summary = estate_report.get("estate_summary", {})
    by_bucket = summary.get("by_complexity_bucket", {})
    by_pattern = summary.get("by_target_pattern", {})

    story.append(Paragraph("Executive summary", styles["h1"]))
    exec_rows = [
        ["Metric", "Value"],
        ["Packages scanned", str(estate_report.get("package_count", 0))],
        ["Parse failures", str(estate_report.get("failure_count", 0))],
        ["Bulk-convertible (low/medium)", str(summary.get("bulk_convertible_count", 0))],
        ["Needs design review (high/very_high)", str(summary.get("needs_design_review_count", 0))],
        ["Estimated effort — likely (hours)", str(summary.get("estimated_total_hours", 0))],
    ]
    low_h = summary.get("estimated_low_hours")
    high_h = summary.get("estimated_high_hours")
    if low_h or high_h:
        exec_rows.append([
            "Estimated effort — range (low / high)",
            f"{low_h or 0}h / {high_h or 0}h",
        ])
    saved_h = summary.get("mcp_automated_hours_saved")
    if saved_h:
        exec_rows.append([
            "Hand-authoring hours absorbed by MCP tooling",
            f"{saved_h}h (informational)",
        ])
    dedup_h = summary.get("deduplication_hours_saved")
    if dedup_h:
        exec_rows.append([
            "Additional hours saved via shared linked services",
            f"{dedup_h}h (recommended action — see consolidation section)",
        ])
    consol_h = summary.get("consolidation_potential_hours_saved")
    if consol_h:
        exec_rows.append([
            "Potential hours saved via pipeline consolidation",
            f"{consol_h}h (judgment call — see consolidation section)",
        ])
    exec_rows.append(["Manual-required items", str(summary.get("manual_required_total", 0))])
    if cost_estimate:
        exec_rows.append(["Projected monthly run cost (USD)", f"${cost_estimate.get('monthly_total_usd', 0):,.2f}"])
        exec_rows.append(["Projected annual run cost (USD)", f"${cost_estimate.get('annual_total_usd', 0):,.2f}"])
    story.append(_table(exec_rows, [3.0 * inch, 3.5 * inch]))
    story.append(Spacer(1, 0.2 * inch))

    # -- Complexity / pattern breakdown --
    story.append(Paragraph("Estate composition", styles["h1"]))
    story.append(Paragraph("By complexity bucket", styles["h2"]))
    bucket_rows = [["Bucket", "Packages"]] + [
        [b, str(by_bucket.get(b, 0))] for b in ("low", "medium", "high", "very_high")
    ]
    story.append(_table(bucket_rows, [2.0 * inch, 1.0 * inch]))
    story.append(Spacer(1, 0.15 * inch))

    story.append(Paragraph("By target pattern", styles["h2"]))
    pattern_rows = [["Target pattern", "Packages"]] + [
        [p, str(c)] for p, c in sorted(by_pattern.items(), key=lambda kv: -kv[1])
    ]
    story.append(_table(pattern_rows, [3.5 * inch, 1.0 * inch]))

    # -- Wave plan --
    if waves and waves.get("waves"):
        story.append(PageBreak())
        story.append(Paragraph("Recommended migration waves", styles["h1"]))
        wave_caption = (
            f"{waves.get('wave_count', 0)} waves \u2014 "
            f"total estimated effort: {waves.get('total_estimated_hours', 0)}h"
        )
        if waves.get("estate_setup_hours"):
            wave_caption += (
                f" (includes {waves['estate_setup_hours']}h one-time estate bring-up in Wave 1)"
            )
        if waves.get("learning_curve_applied"):
            wave_caption += " — learning-curve discount applied inside each wave."
        story.append(Paragraph(wave_caption, styles["body"]))
        story.append(Spacer(1, 0.1 * inch))
        wave_rows = [["#", "Label", "Strategy", "Pkgs", "Hours"]]
        for w in waves["waves"]:
            hours_cell = str(w["estimated_hours"])
            if w.get("setup_surcharge_hours"):
                hours_cell += f" (incl. {w['setup_surcharge_hours']}h setup)"
            wave_rows.append([
                str(w["wave"]),
                w["label"],
                w.get("strategy", ""),
                str(w["package_count"]),
                hours_cell,
            ])
        story.append(_table(wave_rows, [0.4 * inch, 2.6 * inch, 1.3 * inch, 0.6 * inch, 1.3 * inch]))

    # -- Consolidation & deduplication opportunities --
    consolidation = estate_report.get("consolidation")
    if consolidation:
        story.append(PageBreak())
        story.append(Paragraph("Consolidation & deduplication opportunities", styles["h1"]))

        # --- Deduplication (safe, recommended) ---
        dedup = consolidation.get("deduplication", {})
        story.append(Paragraph("Deduplication (recommended)", styles["h2"]))
        story.append(Paragraph(_esc(dedup.get("recommended_action", "")), styles["body"]))
        if dedup.get("candidates"):
            story.append(Paragraph(
                f"<b>Total hours saved if shared:</b> {dedup.get('total_hours_saved', 0)}h",
                styles["body"],
            ))
            story.append(Spacer(1, 0.1 * inch))
            dedup_rows = [["Connection", "Type", "Used in N packages", "Hours saved"]]
            for c in dedup["candidates"][:20]:
                dedup_rows.append([
                    _esc(c.get("label", "")),
                    _esc(c.get("connection_type", "")),
                    str(c.get("duplicate_count", 0)),
                    f"{c.get('hours_saved_if_shared', 0)}h",
                ])
            story.append(_table(dedup_rows, [3.0 * inch, 1.2 * inch, 1.4 * inch, 1.0 * inch]))
            extras = max(0, len(dedup["candidates"]) - 20)
            if extras:
                story.append(Paragraph(f"…and {extras} more candidate(s).", styles["small"]))
        story.append(Spacer(1, 0.2 * inch))

        # --- Consolidation (judgment call) ---
        consol = consolidation.get("consolidation", {})
        story.append(Paragraph("Pipeline consolidation (judgment call)", styles["h2"]))
        story.append(Paragraph(_esc(consol.get("guidance", "")), styles["body"]))
        if consol.get("candidates"):
            story.append(Paragraph(
                f"<b>Potential hours saved:</b> {consol.get('potential_hours_saved', 0)}h "
                "(net of consolidation build effort)",
                styles["body"],
            ))
            story.append(Spacer(1, 0.1 * inch))
            consol_rows = [["Group fingerprint", "Shape", "Pkgs", "Net hours"]]
            for c in consol["candidates"][:20]:
                consol_rows.append([
                    _esc(c.get("fingerprint", "")),
                    _esc(c.get("shape", ""))[:60],
                    str(c.get("package_count", 0)),
                    f"{c.get('estimated_hours_saved', 0)}h",
                ])
            story.append(_table(consol_rows, [1.1 * inch, 3.4 * inch, 0.6 * inch, 1.4 * inch]))
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph(
                "<i>Tradeoffs:</i> consolidation reduces N pipelines to 1 with parameters. "
                "Pros: single deployment, single alerting target, less duplication. "
                "Cons: ownership/lineage becomes implicit, debugging requires parameter context, "
                "per-package SLAs must be re-modelled. Recommended only when packages share an "
                "owner and schedule.",
                styles["small"],
            ))

    # -- Cost detail --
    if cost_estimate:
        story.append(PageBreak())
        story.append(Paragraph("Projected monthly cost (USD)", styles["h1"]))
        story.append(Paragraph(_esc(cost_estimate.get("note", "")), styles["small"]))
        story.append(Spacer(1, 0.1 * inch))
        cost_rows = [["Line item", "Monthly USD", "Basis"]]
        for li in cost_estimate.get("line_items", []):
            cost_rows.append([li["name"], f"${li['monthly_usd']:,.2f}", li["basis"]])
        cost_rows.append(["Total", f"${cost_estimate.get('monthly_total_usd', 0):,.2f}", ""])
        story.append(_table(cost_rows, [3.2 * inch, 1.2 * inch, 2.4 * inch]))

    # -- Per-package detail --
    story.append(PageBreak())
    story.append(Paragraph("Per-package detail", styles["h1"]))
    pkg_rows = [["Package", "Bucket", "Pattern", "Score", "Likely h", "Range (low–high)", "MCP saves", "Manual"]]
    for p in estate_report.get("packages", []):
        likely = p.get("estimated_total_hours", "")
        low = p.get("estimated_low_hours")
        high = p.get("estimated_high_hours")
        saved = p.get("mcp_automated_hours_saved")
        range_cell = f"{low}–{high}" if (low or high) else ""
        saved_cell = f"{saved}h" if saved else ""
        pkg_rows.append([
            p.get("package_name", ""),
            p.get("complexity_bucket", ""),
            p.get("target_pattern", ""),
            str(p.get("complexity_score", "")),
            str(likely),
            range_cell,
            saved_cell,
            str(p.get("manual_required_count", 0)),
        ])
    story.append(_table(
        pkg_rows,
        [1.7 * inch, 0.6 * inch, 1.2 * inch, 0.5 * inch, 0.6 * inch, 0.9 * inch, 0.6 * inch, 0.5 * inch],
    ))

    failures = estate_report.get("failures", [])
    if failures:
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph("Parse failures", styles["h2"]))
        for f in failures:
            story.append(Paragraph(f"\u2022 {_esc(f.get('path', '?'))} \u2014 {_esc(f.get('error', ''))}", styles["small"]))

    doc.build(story)
    return str(out_path)
